### ISSUE TITLE
Erros in schemac generated python schemas

### ISSUE THREAD

**Issue by alichaddad** [threefoldtech/js-ng#252]
# Schemac Erros

## Properties have dash in the name

```toml
category = "kubernetes,proxy,reverse-proxy" (E)
```

```python
Kubernetes = 4
Proxy = 5
Reverse-proxy = 6
```

## Properties with empty default value and object with no class argument

```toml
stats_aggregator = (LO) !tfgrid.workloads.reservation.statsaggregator.1
#id of threebot who is the farmer
farmer_tid = (I)
@url = tfgrid.workloads.reservation.network.1
```

```python
stats_aggregator  = fields.List(fields.Object( )) # should be stats_aggregator = fields.List(fields.Object(TfgridWorkloadsReservationStatsaggregator1))
farmer_tid  = fields.Integer(default= )
```

## Classes used before being defined

Classes definition don't respect definition order

## Default value for ip addresses have incorrect string termiantion

```toml
iprange = "10.10.11.0/24" (iprange)
```

```python
iprange = fields.IPAddress(default="10.10.11.0/24)"
```

## Boolean values
Uses `false` for default boolean values

## Add `id` attr

Schemas in JSX have an id even if not specified in the definition. Should think about whether it should be by default or explicit.
