### ISSUE TITLE
pin prompt-toolkit and ptpython versions to make sure auto-completion is working

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-ng#542]
Some latest versions of ptpython and prompt-toolkit break auto-completion, make sure to pin the latest versions that have it working.

**Comment by abom** [comment]
They seem to have the correct versions:

```toml
ptpython = "^2.0"
prompt-toolkit = "<3.0.0"
```

Will check `jedi` version, I remember we had problems with "0.18.0".
